### ISSUE TITLE
[Bug]: rem_unregistered and cross-seed

### ISSUE THREAD

**Issue by pax0707** [StuffAnThings/qbit_manage#201] opened 2022-12-16 00:22 UTC
### Describe the Bug

Bug/working as intended.

Tagging Torrents with Tracker Errors (and deleting) is done before Checking for Cross-Seed Torrents.

In the case where the torrent is removed from the tracker before cross-seed is added torrent data will be removed and cross-seeded torrents for them will fail because the data was deleted.

criminal.minds.s16e05.1080p.web.h264-ggez as an example
(there's also something funky happening with file locking that causes the copy to recycle instead of the move but I need to look into that some other time)

Could cross-seed be done before removing unregistered? That way only the torrent file would removed and data would remain for cross-seed?

### Logs

https://gist.github.com/pax0707/ca4eeaa839ab825a2caa08933d289dde

### Installation

Unraid

### Version Number

3.4.1

### What branch are you on?

master

**Comment by KnifeFed** [comment] 2023-01-05 18:52
I've been wondering why I keep getting a bunch of errored torrents with "missing files" constantly and this seems like the reason. Would be great with a fix.

**Comment by KyleSanderson** [comment] 2023-01-21 19:30
duplicate of https://github.com/StuffAnThings/qbit_manage/issues/148

**Closed** 2023-05-24 00:49 UTC
Labels: bug, status:added-to-develop
