### ISSUE TITLE
[Bug]: Ratio setting from tracker not kept when noHL is applied.

### ISSUE THREAD

**Issue by Quafley** [StuffAnThings/qbit_manage#218] opened 2023-02-01 12:01 UTC
### Describe the Bug

Let's start with what the docs say. Within the https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#nohardlinks, the wiki states that the default value of max_ratio is none. Please look at the config for my current setup; note I have only added what is relevant to this report.

Flow:
Both series and anime are within one sonarr instance. After that, both are added to 1 qbit instance under the category sonarr. When completed, c_sonarr. This issue is only relevant for the tag 'nyaa'. I have configured it with a max ratio of 1 and an upload speed limit of 512kbps. This works great; everything is paused after a ratio of 1 has been hit.

When the noHL tag is applied to torrents, the upload speed is kept as is. This is good. The max_ratio, however, is removed and replaced with an unlimited ratio. This is also apparent in the logs I have included with this report.

Either the docs don't state the correct default value, or this is a bug where the ratio of a tracker is replaced with -1 when nothing is specified.

### Config

```yaml
tracker:
  nyaa:
    tag: nyaa
    notifiarr: nyaa
    max_ratio: 1
    limit_upload_speed: 512

nohardlinks:
  sonarr_c:
    exclude_tags:
    cleanup: true
    max_seeding_time: 28800
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
```

### Logs

https://gist.github.com/Quafley/09335ccc8a04541f989bf2fd32c301b2

### Screenshots

![image](https://user-images.githubusercontent.com/44779473/216036828-230b17b1-5da4-4e90-8b19-d22c89ac030c.png)

### Installation

Unraid

### Version Number

3.4.2

### What branch are you on?

master

**Comment by Quafley** [comment] 2023-02-01 12:17
![image](https://user-images.githubusercontent.com/44779473/216040244-c6b529cf-149f-4e79-bd2f-34eacee1ed26.png)

**Comment by bakerboy448** [comment] 2023-02-01 12:25
Duplicate of https://github.com/StuffAnThings/qbit_manage/issues/196

this was already fixed and confirmed to be working.....

**Comment by Quafley** [comment] 2023-02-01 13:29
Thanks for the reply baker. This has been tested on the latest build available. I have just done another run, and it does not work. Ratio limit is removed on noHL add.

```yml
Applying permissions to /config
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 04 (1080p) [3CF581B7].mkv     |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 05 (1080p) [0FF4B53A].mkv     |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 06 (1080p) [9E88E130].mkv     |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
|    Torrent Name: Summer.Time.Rendering.S01E17.1080p.DSNP.WEB-DL.AAC2.0.H.264-VARYG.mkv             |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
|    Torrent Name: [SubsPlease] Kimetsu no Yaiba - Mugen Ressha-hen (01-07) (1080p) [Batch]          |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
|    Torrent Name: Tokyo Revengers S02E02 UNCENSORED 1080p WEB H.264 AAC -Tsundere-Raws (DSNP).mkv   |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
| Updated 7 new tags.  
```
```yml
|================================ Tagging Torrents with No Hardlinks ================================|
|    Torrent Name: Tokyo Revengers S02E02 UNCENSORED 1080p WEB H.264 AAC -Tsundere-Raws (DSNP).mkv   |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: Summer.Time.Rendering.S01E17.1080p.DSNP.WEB-DL.AAC2.0.H.264-VARYG.mkv             |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 05 (1080p) [0FF4B53A].mkv     |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 06 (1080p) [9E88E130].mkv     |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: Summertime Rendering - S01E01~E13 - MULTi 1080p WEB H.264 -NanDesuKa (DSNP)       |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: [SubsPlease] Kimetsu no Yaiba - Mugen Ressha-hen (01-07) (1080p) [Batch]          |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 04 (1080p) [3CF581B7].mkv     |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
| No torrents found in the category (race-tv) defined under nohardlinks attribute in the config. Please check if this matches with any category in qbittorrent and has 1 or more torrents. |
| Tag/set share limits for 7 .torrents.                                                              |
```
Automatic torrent management is on.
If you want I can also supply a docker compose.

**Comment by bakerboy448** [comment] 2023-02-01 16:25
Can you confirm it's still an issue on dev please

**Comment by Quafley** [comment] 2023-02-01 20:13
Hi, just tested it on nightly. Result is the same:
![image](https://user-images.githubusercontent.com/44779473/216152963-22a5be24-85a1-4111-8019-e981ac2f73a3.png)
```yml
|========================================== Updating Tags ===========================================|
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 04 (1080p) [3CF581B7].mkv     |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 05 (1080p) [0FF4B53A].mkv     |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
|    Torrent Name: Tokyo Revengers S02E02v2 UNCENSORED 1080p WEB H.264 AAC -Tsundere-Raws (DSNP).mkv |
|         New Tag: nyaa                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|  Limit UL Speed: 512 kB/s                                                                          |
|     Share Limit: Max Ratio = 1.0                                                                   |
| Updated 3 new tags.                                                                                |
|================================== Removing Unregistered Torrents ==================================|
| No unregistered torrents found.                                                                    |
|==================================== Rechecking Paused Torrents ====================================|
|================================ Tagging Torrents with No Hardlinks ================================|
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 05 (1080p) [0FF4B53A].mkv     |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: [SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 04 (1080p) [3CF581B7].mkv     |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
|    Torrent Name: Tokyo Revengers S02E02v2 UNCENSORED 1080p WEB H.264 AAC -Tsundere-Raws (DSNP).mkv |
|       Added Tag: noHL                                                                              |
|         Tracker: http://nyaa.tracker.wf:7777                                                       |
|     Share Limit: Max Ratio = -1, Max Seed Time = 28800 min                                         |
| No torrents found in the category (race-tv) defined under nohardlinks attribute in the config. Please check if this matches with any category in qbittorrent and has 1 or more torrents. |
| Tag/set share limits for 3 .torrents.   
```

**Comment by Quafley** [comment] 2023-02-03 08:48
If you want me to pull the next releases from nightly or try something else, let me know. :) I don't pull the newest nightly, unless necessary

**Comment by Quafley** [comment] 2023-02-23 23:10
Status?

**Comment by bakerboy448** [comment] 2023-03-31 16:16
PR is up that I think fixes this, with some logic changes

Previous State for noHardLinks:
- Max Ratio from noHL Cat
- Max Time from noHL Cat
- MinSeedTime from Tracker if exists; else noHL Cat

Future State for noHardLinks:
For Max Ratio, Max Time, and MinSeedTime:
- Larger of Tracker or noHL Cat
- if tracker and noHL Cat are not set use -1 (unlimited); use 0 for MinSeedTime

https://github.com/StuffAnThings/qbit_manage/pull/247

Local can test with the below running from the QBM Repo directory....strongly suggest running with dry-run....it needs testing.

```bash
git fetch origin pull/247/head:lint-nohllogic
git checkout lint-nohllogic
```
or if auth'd with git

```bash
gh pr checkout 247
```

unsure how to test for docker

**Comment by bakerboy448** [comment] 2023-03-31 16:19
RCA for this issue is due to the noHL category being hardcoded for ratio/time goal

https://github.com/StuffAnThings/qbit_manage/blob/b7be46b5f87d6d7fcf5951301426b41f8d0868dc/modules/qbittorrent.py#L496-L497

**Comment by bakerboy448** [comment] 2023-03-31 18:45
fixed in dev

**Comment by Quafley** [comment] 2023-03-31 19:53
Hi,
[qbitmanage.log](https://github.com/StuffAnThings/qbit_manage/files/11125471/qbitmanage.log)

It seems that the newest build crashes. I've provied the qbitmanage.log in DEBUG mode.

**Comment by bakerboy448** [comment] 2023-03-31 20:08
```
diff --git a/modules/qbittorrent.py b/modules/qbittorrent.py
index b0c3ed2..104489c 100755
--- a/modules/qbittorrent.py
+++ b/modules/qbittorrent.py
@@ -537,9 +537,6 @@ class Qbt:
                         # Checks for any hardlinks and not already tagged
                         # Cleans up previously tagged noHL torrents that no longer have hardlinks
                         if has_nohardlinks:
-                            # Will only tag new torrents that don't have noHL tag
-                            if "noHL" not in torrent.tags:
-                                add_tag_no_hl(add_tag=True)
                             tracker = self.config.get_tags(torrent.trackers)
                             # Determine min_seeding_time.
                             # If only tracker setting is set, use tracker's min_seeding_time
@@ -577,6 +574,9 @@ class Qbt:
                                 max_seeding_time = tracker["max_seeding_time"]
                             elif nohardlinks[category]["max_seeding_time"]:
                                 max_seeding_time = nohardlinks[category]["max_seeding_time"]
+                            # Will only tag new torrents that don't have noHL tag
+                            if "noHL" not in torrent.tags:
+                                add_tag_no_hl(add_tag=True)
                             # Deletes torrent with data if cleanup is set to true and meets the ratio/seeding requirements
                             if nohardlinks[category]["cleanup"] and len(nohardlinks[category]) > 0:
                                 tor_reach_seed_limit = self.has_reached_seed_limit(
```
i think this may be a possible fix?; @bobokun will check into it

**Comment by bobokun** [comment] 2023-03-31 22:15
@Quafley  can you try again?

**Comment by Quafley** [comment] 2023-03-31 22:26
Hi, 

I just pulled the latest nightly version, the error message we got before has been resolved. 

I will now test if the thing, for which the ticket was initially created, has been resolved.

Thanks for the fast response baker and bobo.

**Comment by bakerboy448** [comment] 2023-03-31 23:35
For posterity - v3.5.0 + 382a9af45f89ba5ebb83da04cee1fe1fa0983304 should be the fix

**Closed** 2023-04-04 01:58 UTC
Labels: bug, status:added-to-develop
