### ISSUE TITLE
[FR]: Delete torrents if paused for a certain amount of time

### ISSUE THREAD

**Issue by hacshacdgacs** [StuffAnThings/qbit_manage#465] opened 2024-01-10 01:06 UTC
### Is your feature request related to a problem? Please elaborate.

Due to the way I've had to set things up my cross-seeded torrents have to be added in a paused state and are then checked to see if there's any match. If they aren't match they then remain paused which requires me to manually go through and remove them (because they haven't started trackers don't register them as a hit&run and the torrents don't believe they're missing files).

### Describe the solution you'd like

An ability to automatically remove torrents if they've been paused for a certain amount of time (say 1 day).

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I tried implementing another cross-seed but was unable to get it to work on my system

### Who will this benefit?

Anyone who wants to automatically remove torrents that have been left in a paused state.

**Comment by bakerboy448** [comment] 2024-01-10 01:09
Duplicate of https://github.com/StuffAnThings/qbit_manage/issues/115

**Closed by bakerboy448** 2024-01-10 01:09 UTC
Labels: feature request
