### ISSUE TITLE
[FR]: Change Category based on Tracker

### ISSUE THREAD

**Issue by DaZuru** [StuffAnThings/qbit_manage#423] opened 2023-10-18 19:39 UTC
### Is your feature request related to a problem? Please elaborate.

Using Orbit/Radarr and Jackett. I have private trackers to search. Once a torrent is downloaded from a Private Tracker, have it look at the Torrent list and change the category to a pre-setup Qbittorrent category. I do it manually now by selecting Trackers in Qbittorrent and then changing the category for any Private Trackers.

### Describe the solution you'd like

Once a torrent is downloaded from a Private Tracker, have it look at the Torrent list and change the category to a pre-setup Qbittorrent category.

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

I do it manually now by selecting Trackers in Qbittorrent and then changing the category for any Private Trackers.

### Who will this benefit?

Anyone that wants to make sure they continue to seed and track their Private Torrent reponsibilities.

**Comment by bobokun** [comment] 2023-10-18 20:45
This is a duplicate of #200

**Closed by bobokun** 2023-10-18 20:45 UTC
Labels: feature request
